// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOkCkt9GjBmJXa-qk2av_ovzoT07ZUKI',
    appId: '1:75768296549:web:fb15668ba214261db5828c',
    messagingSenderId: '75768296549',
    projectId: 'carevive-7f9a0',
    authDomain: 'carevive-7f9a0.firebaseapp.com',
    storageBucket: 'carevive-7f9a0.appspot.com',
    measurementId: 'G-LM0L4CGSG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcc7UIAPDe0Wt7RsiUx_KUsdQ7pJ2MEX4',
    appId: '1:75768296549:android:00ad765c8421a60fb5828c',
    messagingSenderId: '75768296549',
    projectId: 'carevive-7f9a0',
    storageBucket: 'carevive-7f9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0pBe4JfsirJjYXmG1EFRDoWMQPvAUhIw',
    appId: '1:75768296549:ios:d455095a45a6176fb5828c',
    messagingSenderId: '75768296549',
    projectId: 'carevive-7f9a0',
    storageBucket: 'carevive-7f9a0.appspot.com',
    iosBundleId: 'com.example.carevive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0pBe4JfsirJjYXmG1EFRDoWMQPvAUhIw',
    appId: '1:75768296549:ios:d455095a45a6176fb5828c',
    messagingSenderId: '75768296549',
    projectId: 'carevive-7f9a0',
    storageBucket: 'carevive-7f9a0.appspot.com',
    iosBundleId: 'com.example.carevive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGOkCkt9GjBmJXa-qk2av_ovzoT07ZUKI',
    appId: '1:75768296549:web:ecc152f645c8f35cb5828c',
    messagingSenderId: '75768296549',
    projectId: 'carevive-7f9a0',
    authDomain: 'carevive-7f9a0.firebaseapp.com',
    storageBucket: 'carevive-7f9a0.appspot.com',
    measurementId: 'G-ZW1D7L9026',
  );
}
